version: '3.8'

services:
  backend:
    build:
      context: ./server
      dockerfile: dockerfile
    ports:
      - "5000:5000"
    networks:
      - app-network

  frontend:
    build:
      context: ./web
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network

  auth:
    build: ./auth
    ports:
      - "5001:5001"
    networks:
      - app-network

volumes:
  db_data:
  scripts:

networks:
  app-network:
