version: '3.8'

services:

  server:
    container_name: main
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - app-network
    volumes:
      - ./logs:/app/logs:rw
      - ./scripts:/app/scripts:rw
    privileged: true
    environment:
      FLASK_ENV: development

  web:
    build:
      context: ./server/static/js
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - app-network
    volumes:
      - ./logs:/app/logs
      - ./scripts:/app/scripts

  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    depends_on:
      - server
    networks:
      - app-network
    environment:
      FLASK_ENV: development


volumes:
  scripts:
  logs:

networks:
  app-network:
    driver: bridge
